apiVersion: v1
kind: Service
metadata:
  name: post-microservice-service
spec:
  selector:
    app: post-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30333  # Choose a port number in the range 30000-32767
  type: NodePort
