name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build # name of the job
    runs-on: ubuntu-latest # Defines where the job will run on

    strategy: # To define a set of configurations for the job to run in.
      matrix: # Child key of strategy. It creates an array of different job configurations 
        node-version: [20.x]  # Updated to match your local version

    steps:
    - name: Checkout code 
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2 # It specifies an action to be executed as part of a step in your job
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # Optionally enable caching

    - name: Install dependencies
      run: npm ci  # Use npm ci for a more reliable dependency install

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: npm test

  deploy:
    name: Deploy
    needs: test  # This job depends on the 'test' job
    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
    - name: Docker build and push
      run: |
        docker build -t my-app:${{ github.sha }} .
        docker push my-app:${{ github.sha }}
